[server]
address = "0.0.0.0"
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
